
apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  labels:
    app: gogs
spec:
  type: NodePort
  selector:
    app: gogs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  # Optional: specify the node port or let Kubernetes allocate one
