apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp
spec:
  type: NodePort
  selector:
    app: wp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional: specify the node port or let Kubernetes allocate one
